name: Build ThunderInterfaces on Linux

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Thunder:
    uses: rdkcentral/Thunder/.github/workflows/Linux build template.yml@development/actions-pep668-error # change back to master

  ThunderInterfacesMaster:
    needs: Thunder
    if: ${{ !contains(github.event.pull_request.body, '[ThunderInterfaces-Linux-template]') }}
    uses: rdkcentral/ThunderInterfaces/.github/workflows/Linux build template.yml@master

  ThunderInterfacesDevelopment:
    needs: Thunder
    if: contains(github.event.pull_request.body, '[ThunderInterfaces-Linux-template]')
    uses: rdkcentral/ThunderInterfaces/.github/workflows/Linux build template.yml@${{github.ref}}

  ThunderClientLibraries:
    needs: [ThunderInterfacesMaster, ThunderInterfacesDevelopment]
    uses: rdkcentral/ThunderClientLibraries/.github/workflows/Linux build template.yml@master

  ThunderNanoServices:
    needs: [ThunderInterfacesMaster, ThunderInterfacesDevelopment]
    uses: rdkcentral/ThunderNanoServices/.github/workflows/Linux build template.yml@master

  ThunderNanoServicesRDK:
    needs: [ThunderInterfacesMaster, ThunderInterfacesDevelopment]
    uses: WebPlatformForEmbedded/ThunderNanoServicesRDK/.github/workflows/Linux build template.yml@master
